[package]
name = "vuur_compile"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4"
log = "0.4"
vuur_parse = { path = "../vuur_parse" }
