[package]
name = "vuur_parse"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
itertools = "0.10"
smol_str = "0.1"
unicode-width = "0.1"
vuur_lexer = { path = "../vuur_lexer" }
